#!/bin/bash
# set -o nounset
shopt -s extglob
SVGDIR=$1
NAMED="${2:-antmode}"
ANIMONE="${3:-"wait"}"
ANIMTWO="${4:-"progress"}"
#conditions should be met first

if [ -n "$1" ]; then
	if [ -d "$1" ]; then
		if [ ! -f "$1/manifest.hl" ]; then
			echo "All conditions met, proceeding with conversion..."
		else
			echo "Error: $1 already has a manifest.hl file."
			exit 1
		fi
	else
		echo "Error: $1 is not a directory."
		exit 1
	fi
else
	echo "Error: No argument provided."
	exit 1
fi

#prepare directory, remove any extraneous files

cd "$SVGDIR"
rm -rf cursors *_24.svg
mkdir cursors $ANIMONE $ANIMTWO
mv $ANIMONE-* $ANIMONE
mv $ANIMTWO-* $ANIMTWO
#create a containing folder with name of icon

for file in *.svg; do
	file_contents="resize_algorithm = bilinear
define_size = 64, $file"
	direct="${file%.svg}"
	mkdir -- "$direct"
	mv -- "$file" "$direct"
	echo "$file_contents" >$direct/meta.hl
done

#wait cursor meta
function process_meta() {
	local ANIM="$1"
	echo "resize_algorithm = bilinear
define_size = 64, $ANIM-01.svg,500
define_size = 64, $ANIM-02.svg,500
define_size = 64, $ANIM-03.svg,500
define_size = 64, $ANIM-04.svg,500
define_size = 64, $ANIM-05.svg,500
define_size = 64, $ANIM-06.svg,500
define_size = 64, $ANIM-07.svg,500
define_size = 64, $ANIM-08.svg,500
define_size = 64, $ANIM-09.svg,500
define_size = 64, $ANIM-10.svg,500
define_size = 64, $ANIM-11.svg,500
define_size = 64, $ANIM-12.svg,500
" >>$ANIM/meta.hl
}
#progress cursor meta

process_meta $ANIMONE
process_meta $ANIMTWO

mv !(cursors) ./cursors
rm cursors/index.theme

echo "[Icon Theme]
Name=$NAMED
Comment=generated by hyprman
" >>index.theme

echo "name = $NAMED
description = let there be ants
version = 0.1
cursors_directory = cursors
" >>manifest.hl

hyprcursor-util --create .
